name: Linting and Formatting

on: [pull_request]

jobs:
  lintingAndFormatting:
    name: Linting and Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Code Linting
        run: npm run lint:fix

      - name: Code formatting
        run: npm run format:fix
